### ISSUE TITLE
Facebook Sign-in Issues

### ISSUE THREAD

**Issue by rgcrypto** [steemit/steemit.com#53]
Hi! I am managing the facebook page and many people have come to me with this issue:

1. They sign-in via Facebook
2. Facebook tells them their account is already linked to steemit

OR

1. They sign-in via Facebook
2. Create a password
3. Try to login and their account don't even exist but when they try to sign-in their account is already linked.
4. They try via reddit and it says the username is already taken. (but doesn't appear on the website)

So far:
@fatlilboy
@darknesskicker 
@leighton34 
@tylermyler
(more coming as soon as they give me their usernames)

**Comment by jcalfee** [comment]
We had a bug.. those accounts were not being created at all on the blockchain.  It is fixed and the account create should let everyone try again with the same name.

**Comment by rgcrypto** [comment]
Thank you

**Comment by celiachua** [comment]
Hi, i tried to create @alicehuca too but i can't.

**Comment by SteemitFbAdmin** [comment]
This issue wasn't solved. Here is the issue she is facing: 

>I tried to re-register, since I still can't log in, and I got the following error:  Couldn't create account. Server returned the following error:
10 assert_exception: Assert Exception creator.balance >= o.fee: Insufficient balance to create account {"creator.balance":"2.320 STEEM","required":"10.000 STEEM"} th_a steem_evaluator.cpp:89 do_apply {"op"😞"account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"darknesskicker","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6K4Dsee35ZAVbqezZXV8GqwBT5pzNvgAxiFCTouKHAepndzgQN",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6XxbAnKXK9K9tnomQvbwgocnbrWmda28ADRQBahb7SF41z6Huz",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6PJQaS5eKYZAYtG8Qg61cmetcCipJBrNWAT7krqZ8LAvDMHPLT",1]]},"memo_key":"STM7dkRgK5B2ZvvSVi4YdQTYogf42iBWHALWu3ukYYCA7qwjkCDLR","json_metadata":""}]} th_a database.cpp:2975 _apply_transaction {"trx":{"ref_block_num":47046,"ref_block_prefix":1084328247,"expiration":"2016-09-05T08:50:42","operations":[["account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"darknesskicker","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6K4Dsee35ZAVbqezZXV8GqwBT5pzNvgAxiFCTouKHAepndzgQN",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6XxbAnKXK9K9tnomQvbwgocnbrWmda28ADRQBahb7SF41z6Huz",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6PJQaS5eKYZAYtG8Qg61cmetcCipJBrNWAT7krqZ8LAvDMHPLT",1]]},"memo_key":"STM7dkRgK5B2ZvvSVi4YdQTYogf42iBWHALWu3ukYYCA7qwjkCDLR","json_metadata":""}]],"extensions":[],"signatures"😞"1f58591aa1f95febdc9d2e224dfe2ee8ed7f1495dbe09b1056a5f5dcd87a6779247532e5822b21add505114f377522b6b4519ed94b40ab99c00b6421ccd2a9c45c"]}} th_a database.cpp:2979 _apply_transaction {"trx":{"ref_block_num":47046,"ref_block_prefix":1084328247,"expiration":"2016-09-05T08:50:42","operations":[["account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"darknesskicker","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6K4Dsee35ZAVbqezZXV8GqwBT5pzNvgAxiFCTouKHAepndzgQN",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6XxbAnKXK9K9tnomQvbwgocnbrWmda28ADRQBahb7SF41z6Huz",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6PJQaS5eKYZAYtG8Qg61cmetcCipJBrNWAT7krqZ8LAvDMHPLT",1]]},"memo_key":"STM7dkRgK5B2ZvvSVi4YdQTYogf42iBWHALWu3ukYYCA7qwjkCDLR","json_metadata":""}]],"extensions":[],"signatures"😞"1f58591aa1f95febdc9d2e224dfe2ee8ed7f1495dbe09b1056a5f5dcd87a6779247532e5822b21add505114f377522b6b4519ed94b40ab99c00b6421ccd2a9c45c"]}} th_a database.cpp:696 push_transaction digest 4e0d9afbf380c92ba0c100dd390a3927ea52f7cbd99d7b8e53d0d3db82019d1c transaction c6b73789a140e231cd570109102700000000000003535445454d000005737465656d0e6461726b6e6573736b69636b657201000000000102bb7a51ffd4209487d95f5155e27e1047527dc09b0c5bdee1369c3f37f8246f92010001000000000102d8c67fb1e20a7a4ad3fdeea6901e053657fa88189a80eddc08fbd32fa33f2c4c010001000000000102c51d9887db2fcba23d535ada89b4208211623964608e949dce425654793ab29a010003699e7870326fc77289a871b0d44fda6438119105c0d5c9d6e5f8e3beb379077b0000011f58591aa1f95febdc9d2e224dfe2ee8ed7f1495dbe09b1056a5f5dcd87a6779247532e5822b21add505114f377522b6b4519ed94b40ab99c00b6421ccd2a9c45c {"ref_block_num":47046,"ref_block_prefix":1084328247,"expiration":"2016-09-05T08:50:42","operations":[["account_create",{"fee":"10.000 STEEM","creator":"steem","new_account_name":"darknesskicker","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6K4Dsee35ZAVbqezZXV8GqwBT5pzNvgAxiFCTouKHAepndzgQN",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6XxbAnKXK9K9tnomQvbwgocnbrWmda28ADRQBahb7SF41z6Huz",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6PJQaS5eKYZAYtG8Qg61cmetcCipJBrNWAT7krqZ8LAvDMHPLT",1]]},"memo_key":"STM7dkRgK5B2ZvvSVi4YdQTYogf42iBWHALWu3ukYYCA7qwjkCDLR","json_metadata":""}]],"extensions":[],"signatures":("1f58591aa1f95febdc9d2e224dfe2ee8ed7f1495dbe09b1056a5f5dcd87a6779247532e5822b21add505114f377522b6b4519ed94b40ab99c00b6421ccd2a9c45c"]}

**Comment by SteemitFbAdmin** [comment]
Christine Hughes-Wiklund

**Comment by roadscape** [comment]
@SteemitFbAdmin in that error message, I see the expiration is `2016-09-05T08:50:42`, so this must be an old issue
